export const Comments: CommentType[] = [
  {
    community: "gaming",
    post: "1234",
    created_at: "18h ago",
    content: "I find this post really offensive, could you please delete?",
    user: "frojak4",
    upvotes: 13,
  },
  {
    community: "cats",
    post: "5678",
    created_at: "2h ago",
    content: "Does anyone elses cat judge them for eating instant ramen?",
    user: "whiskerQueen",
    upvotes: 42,
  },
  {
    community: "cooking",
    post: "4321",
    created_at: "4d ago",
    content: "My lasagna caught fire. Is this normal? Asking for a friend.",
    user: "burntToastMaster",
    upvotes: 7,
  },
  {
    community: "travel",
    post: "9876",
    created_at: "3h ago",
    content: "If anyone tells you that a camel ride is relaxing, THEYRE LYING.",
    user: "nomadNelly",
    upvotes: 25,
  },
  {
    community: "gaming",
    post: "1235",
    created_at: "10m ago",
    content: "This post gave me +10 XP in sarcasm. Thanks, OP.",
    user: "levelUpLarry",
    upvotes: 69,
  },
  {
    community: "dogs",
    post: "1122",
    created_at: "8h ago",
    content: "Why does my dog stare at me when I eat? He has a full bowl.",
    user: "borklord9000",
    upvotes: 55,
  },
  {
    community: "tech",
    post: "1010",
    created_at: "1d ago",
    content:
      "I coded all night and accidentally created an AI that orders pizza. Help?",
    user: "debuggedDave",
    upvotes: 98,
  },
];
